import type { Product } from "@/types";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Coca Cola 330ml",
    sku: "BEV-001",
    price: 15,
    stock: 48,
    category: "Beverages",
    lowStockThreshold: 20,
  },
  {
    id: "2",
    name: "Bread - White Loaf",
    sku: "BAK-001",
    price: 25,
    stock: 12,
    category: "Bakery",
    lowStockThreshold: 10,
  },
  {
    id: "3",
    name: "Milk 1L",
    sku: "DAI-001",
    price: 35,
    stock: 8,
    category: "Dairy",
    lowStockThreshold: 15,
  },
  {
    id: "4",
    name: "Rice 5kg",
    sku: "GRO-001",
    price: 120,
    stock: 25,
    category: "Groceries",
    lowStockThreshold: 10,
  },
  {
    id: "5",
    name: "Eggs (12 pack)",
    sku: "DAI-002",
    price: 45,
    stock: 5,
    category: "Dairy",
    lowStockThreshold: 8,
  },
  {
    id: "6",
    name: "Bottled Water 1.5L",
    sku: "BEV-002",
    price: 10,
    stock: 60,
    category: "Beverages",
    lowStockThreshold: 30,
  },
];